### ISSUE TITLE
Wallet stuck on "attempting to sync for multiple days

### ISSUE THREAD

**Issue by annisimpson** [cake-tech/upptime-cakewallet#1115]
Steps to reproduce:
- Open Cake Wallet on iOS 17.5.1 on iPhone 14. 
- Cake Wallet version 4.18.2.
- Enter the correct PIN. 
- Open the primary account.
- Wait for connection to sync.

Expected behavior:
- Open Cake in device. 
- Enter PIN. 
- Cake connects. 
- Cake syncs with the server. 
- Cake updates with correct resource amounts. 

Actual behavior:
- Cake gets stuck on "attempting to sync" and never actually does. Has lasted for days. 

Attempted troubleshooting:
- Turning the device on and off. 
- Closing the app and it opening it again. 
- Ensuring it is up to date. 
- Reconnecting. 
- Rescanning from an earlier date. 

Outcome:
- Eternal "attempting to sync."

**Comment by tuxpizza** [comment]
Hi, this is not the correct repository for bug reports, please post an issue here: https://github.com/cake-tech/cake_wallet/issues

And in that report, please add a couple other information like crypocurrency type you are attempting to sync, and the current node you are using and other nodes if you have tried

**Comment by annisimpson** [comment]
Thank you. I will do that.,
