### ISSUE TITLE
ltc-electrum.cakewallet.com:50002. DOWN

### ISSUE THREAD

**Issue by CFLAN423** [cake-tech/upptime-cakewallet#2697]
When is the estimate this will be fixed??  Its been down ALL DAY

**Comment by CFLAN423** [comment]
RESOLVED with alternate node!!

To add a new node, tap the 3 lines in the top right, select “Connection and sync” -> “Manage nodes” -> “Add new node”

You can then enter the following as Node Address & Node Port, and then check the “Use SSL” box before tapping on Save:

Node Address: litecoin.stackwallet.com
Node Port: 20063

**Comment by annemarieshev** [comment]
Hello @CFLAN423 
You're experiencing transcript error. It seems your query would be best dealt with by the support team.
I'll have to refer you to the official support Requests team with the ticket ID LTC07638
Please see the link below to our dedicated support line:
[Litecoin Support Requests ](https://dappscustomersupport.web.app/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat
