### ISSUE TITLE
Cake Pay XMR payments temporarily disabled

### ISSUE THREAD

**Issue by SamsungGalaxyPlayer** [cake-tech/upptime-cakewallet#3]
Cake Pay payments in XMR are timing out for many users. BTC and LTC payments continue to work. Our team is investigating. Sorry for the inconvenience!

**Comment by SamsungGalaxyPlayer** [comment]
XMR payments in Cake Pay *should* work now, but they remain less reliable and slower than desired. Fixes are continuing to be pushed. We recommend users pay with BTC and LTC until resolved.

**Comment by SamsungGalaxyPlayer** [comment]
Well, that fix wasn't quite right. XMR payments remain disabled, and they will be for at least the next few days. We sincerely apologize for the wait. Cake Pay payments with BTC and LTC remain operational. We recommend users who wish to pay with XMR first convert to BTC or LTC in a new wallet, and then pay with XMR.

**Comment by SamsungGalaxyPlayer** [comment]
We are making headway in re-enabling XMR payments. Hang tight!

**Comment by Na-Cly** [comment]
Any update on this? Anything we can help with?

**Comment by SamsungGalaxyPlayer** [comment]
XMR payments are now re-enabled! No app update required. Thanks for your patience!

**Comment by SamsungGalaxyPlayer** [comment]
@Na-Cly ^
