### ISSUE TITLE
Cake Pay Mobile: Bitcoin payments temporarily disabled

### ISSUE THREAD

**Issue by SamsungGalaxyPlayer** [cake-tech/upptime-cakewallet#50]
Bitcoin payments for Cake Pay Mobile are temporarily disabled. Cake Pay Web is unaffected.

**Comment by KaSakee** [comment]
For how long bro?

**Comment by SamsungGalaxyPlayer** [comment]
Replaced by https://github.com/cake-tech/upptime-cakewallet/issues/52
