### ISSUE TITLE
Monero coin restores

### ISSUE THREAD

**Issue by lovejiya0213** [cake-tech/upptime-cakewallet#51]
I downloaded a wallet made in China called Monero wallet and made a wallet. I swapped Exodus Bitcoin wallet from Change Now and sent it to Monero wallet, and I left an inquiry because it was confirmed that the transmission was completed in Trackjection, and when I answered to sync from another wallet, it was synchronized at pm22:23 in monero.com wallet, and my coin was transferred at the same time.

**Comment by SamsungGalaxyPlayer** [comment]
Hello! Please email support@cakewallet.com
