### ISSUE TITLE
Cake Pay Mobile: "Exception: Unexpected response http code: 400"

### ISSUE THREAD

**Issue by alt4weirdXMRaddress** [cake-tech/upptime-cakewallet#67]
My apologies if this is an improper way to report the issue. Cake Pay Mobile returns this error when attempting to buy a gift card from any store for any amount using XMR. Multiple wallet versions (Cakewallet 4.6.1 and Cakewallet 4.5.6), multiple connection methods (normal, VPN, Tor), multiple Monero nodes were tested. The error occurs using iOS and XMR; I have not tested for other platforms or currencies.

**Comment by SamsungGalaxyPlayer** [comment]
Hello, please post on https://github.com/cake-tech/cake_wallet
